var sever_data={
	"id":1,
	"title":"",
	"description":"",
	"user":12,
	"theme_type":"dolphin",
	"view":[
		{
			"view":"Hero",
			"controller":"Hero",
			"data":{},
			"img":[
				"http://localhost:8080/img-dolphin/story-cover.jpg",
				"http://localhost:8080/img-dolphin/story-cover-text.jpg"
			]
		},
		{
			"view":"TheGirl",
			"controller":"TheGirl",
			"data":{
				"title":"我钟爱的女子",
				"title2":"问今生",
				"paragraph":[
					{"content":"前世，我在奈何桥边寻找着三生石，望桥下覆水飞逝，流年似旧；百般问，今世尘缘何处觅？算不出今生，不问，却又总是用情深。"},
					{"content":"佛说：相思本无根，为何惹红尘？"},
					{"content":"我说：情丝万缕为她困，奈何往昔醉太深。"},
					{"content":"佛说：来生的情路将是一条荆棘之道，你想清楚了吗？"},
					{"content":"我大笑：我为伊人，愿受尽人间疾苦，只为最后的幸福。"},
					{"content":"佛微笑着，看我走向了来生。"}
				]
			},
			"img":[
				"http://localhost:8080/img-dolphin/angel.jpg",
				"http://localhost:8080/img-dolphin/thegirl5.jpg",
				"http://localhost:8080/img-dolphin/dolphin.jpg"
			]
		},
		{
			"view":"Story",
			"controller":"Story",
			"data":{
				"title":"相思苦",
				"paragraph":[
					{
						"p":[{"content":"我钟爱的女子，你偶然的出现，却让我感到了命中注定的喜悦，就悄然走到了我的身边"}],
						"image":[]
					},
					{
						"p":[],
						"image":[{"url":"/img-dolphin/thegirl4.jpg"}]
					},
					{
						"p":[{"content":"你的柔情渐渐融化了我世界，让我尘封的情感，又重新燃起了激情的火花"}],
						"image":[]
					},
					{
						"p":[{"content":"你出现的日子里，写满了我对你思念的篇章，这柔情的篇章，断了多少心肠，谁在彷徨，谁又在你的身旁，思念的篇章，写在思念你的路上"}],
						"image":[]
					},
					{
						"p":[],
						"image":[{"url":"/img-dolphin/thestory2.jpg"}]
					},
					{
						"p":[{"content":"路两旁，岁月已泛黄，思念的篇章，我低声吟唱，雨后的斜阳，是离别的目光，雨水打湿了眼眶，也无法透过苍凉"}],
						"image":[]
					},
					{
						"p":[],
						"image":[{"url":"/img-dolphin/thegirl1.jpg"}]
					},
					{
						"p":[{"content":"离别倦染了时光，思念的篇章不再流畅，只得把爱深藏，等你回到身旁……"}],
						"image":[]
					},
					{
						"p":[{"content":"路两旁，岁月已泛黄，思念的篇章，我低声吟唱，雨后的斜阳，是离别的目光，雨水打湿了眼眶，也无法透过苍凉"}],
						"image":[]
					},
					{
						"p":[{"content":"风雨情"}],
						"image":[]
					},
					{
						"p":[{"content":"前世的我，听佛说过：你来生的情路，将充满坎坷，唯义无反顾，方能拨云见日"}],
						"image":[]
					},
					{
						"p":[],
						"image":[{"url":"/img-dolphin/thestory3.jpg"}]
					},
					{
						"p":[{"content":"今生你我，风过一程，雨又一程；世俗何能奈我情，为君敢把天下弃；只有你，能让我视繁芜如草芥，唯有你，能让我笑陈规如粪土"}],
						"image":[]
					},
					{
						"p":[],
						"image":[{"url":"/img-dolphin/thestory1.jpg"}]
					},
					{
						"p":[{"content":"朝朝暮暮，只为你等，思恋千年，只为今生。让你我的手，不要松开，让我们在凡尘俗世中义无反顾的爱，最终，我们将到达幸福的彼岸，而那些曲折，将会是我们幸福的乌云线，在天际中遨游"}],
						"image":[]
					}
				]
			},
			"img":[
					"http://localhost:8080/img-dolphin/thegirl4.jpg",
					"http://localhost:8080/img-dolphin/thegirl1.jpg",
					"http://localhost:8080/img-dolphin/thestory1.jpg",
					"http://localhost:8080/img-dolphin/thestory3.jpg"
				]
		},
		{
			"view":"Wedding",
			"controller":"Wedding",
			"data":{
				"title":"天使与海豚",
				"paragraph":[
					{"content":"走过甜酸各半的旅程"},
					{"content":"一个有星的夜，你我有了三生石的誓言"},
					{"content":"你要的不多，只要一个温暖怀抱"},
					{"content":"我给的不多，只有一个到老的誓约"},
					{"content":"这一世，你是我钟爱的女子"},
					{"content":"从此缠绵于彼此"},
					{"content":"下一世，你是我钟爱的女子"},
					{"content":"又一个星夜的开始"},
					{"content":"再一世，你是我钟爱的女子"},
					{"content":"重续三生，彼岸花永不凋零"}
				]
			},
			"img":[
				"http://localhost:8080/img-dolphin/rose-bottom.jpg",
				"http://localhost:8080/img-dolphin/rose-top.jpg"
			]
		},
		{
			"view":"LaVie",
			"controller":"LaVie",
			"data":{"title":"不平凡的平淡"},
			"img":[
					"http://localhost:8080/img-dolphin/food1.jpg",
					"http://localhost:8080/img-dolphin/food2.jpg",
					"http://localhost:8080/img-dolphin/food3.jpg",
					"http://localhost:8080/img-dolphin/food4.jpg",
					"http://localhost:8080/img-dolphin/food5.jpg",
					"http://localhost:8080/img-dolphin/thecouple5.jpg",
					"http://localhost:8080/img-dolphin/thecouple3.jpg",
					"http://localhost:8080/img-dolphin/thecouple4.jpg"
				]
		},
		{
			"view":"Wish",
			"controller":"Wish",
			"data":{
				"content":"尽管一切都来得如此艰难，但一首《天使与海豚》开启了我人生新的篇章。我只想用心把你最美丽的时刻凝固在故事里，等我们老的看不清东西，还可以一段一段的回忆曾经这场美好的相遇。"
			},
			"img":[
				"http://localhost:8080/img-dolphin/sunset.jpg",
				"http://localhost:8080/img-dolphin/thecouple.png",
				"http://localhost:8080/img-dolphin/cover-page-light.jpg"
			]
		},
		{
			"view":"Contact",
			"controller":"Contact",
			"data":{},
			"img":[]
		}
	]
};