window.TPL = {
		'contact': Mustache.compile('    <header>        <h1 class="text-center">Send Your <span class="pink-text">Wishes</span></h1>    </header>    <form>        <div class="form-group">            <textarea class="form-control" rows="3" placeholder="在这里留下你的祝福"></textarea>        </div>        <div class="form-group">            <button class="btn btn-lg btn-default btn-block" type="submit">                <i class="fa fa-envelope fa-lg"></i>                <small>发送祝福</small>            </button>        </div>    </form>    <article class="messages"></article>'),
		'goodnight': Mustache.compile('    <div id="nightsky">        <div class="nightsky-image"></div>    </div>'),
		'hero': Mustache.compile('    <div class="carousel carousel-in"></div>    <div class="carousel carousel-out"></div>'),
		'honeymoon': Mustache.compile('    <header>        <h1></h1>    </header>'),
		'lavie': Mustache.compile('    <header>        <h3 class="text-center">{{title}}</h3>    </header>    <div class="gallery">        <div class="gallery-inner">            <img src="/img-dolphin/food2.jpg">            <img src="/img-dolphin/thecouple5.jpg">            <span>风浪后平静的海面是生命中最美的风景线，喧闹之中感受你的平和与宁静</span>            <img src="/img-dolphin/thegirl6.jpg">            <img src="/img-dolphin/thecouple3.jpg">            <span>幸福，本身就是一种陪伴，而有你的陪伴，是我一生的中最大的幸福</span>            <img src="/img-dolphin/thecouple4.jpg">            <img src="/img-dolphin/food5.jpg">            <span>远离那些纷扰，幸福就是我们生活中每天的点点滴滴</span>            <img src="/img-dolphin/food3.jpg">            <img src="/img-dolphin/food1.jpg">            <img src="/img-dolphin/food4.jpg">        </div>    </div>'),
		'story': Mustache.compile('    <div class="timeline-wrapper">        <div class="timeline">            <div class="line"></div>            <div class="post">                <div class="post-time">{{title}}</div>            </div>            {{#paragraph}}            <div class="post">                {{#image}}                    <img class="post-image" src="{{url}}">                {{/image}}                {{#p}}                    <div class="post-box">{{content}}</div>                {{/p}}            </div>            {{/paragraph}}        </div>    </div>'),
		'thegirl': Mustache.compile('    <div class="shy-girl">        <h1 class="text-center">{{title}}</h1>    </div>    <div class="love-cross clearfix">        <div class="img img-the-boy pull-left"></div>        <div class="img img-the-girl pull-left"></div>        <div class="heart"></div>    </div>    <div class="hesays">        <h3 class="text-center">{{title2}}</h3>        {{#paragraph}}        <p>{{content}}</p>        {{/paragraph}}    </div>'),
		'wedding': Mustache.compile('    <div class="rose-cover top"></div>    <div class="rose-cover bottom"></div>    <header>        <h3>{{title}}</h3>        {{#paragraph}}            <p>{{content}}</p>        {{/paragraph}}    </header>'),
		'wish': Mustache.compile('    <div class="cover">        <div class="cover-top">            <p>{{content}}</p>            <h1 class="script text-center">To be continued...</h1>        </div>        <div class="cover-bottom"></div>    </div>    <!--<div class="bouquet">        <img data-src="img/bouquet.png" class="img-responsive">    </div>-->')
	};
