var sever_data={
	"id":2,
	"title":"",
	"description":"",
	"user":12,
	"theme_type":"origin",
	"view":[
		{
			"view_id":"Hero",
			"controller":"Hero",
			"data":{
				"text":{},
				"img":[
					"http://localhost:8080/img-origin/lavande1.jpg",
					"http://localhost:8080/img-origin/lavande2.jpg"
				]
			}
		},
		{
			"view_id":"TheGirl",
			"controller":"TheGirl",
			"data":{
				"text":{
					"text":"小丫丫，别再躲藏，跟叔叔阿姨们打个招呼"
				},
				"img":[
					"http://localhost:8080/img-origin/thegirl/5.jpg",
					"http://localhost:8080/img-origin/thegirl/4.jpg",
					"http://localhost:8080/img-origin/heart-cross-pink.png"
				]
			}
		},
		{
			"view_id":"TheBigDay",
			"controller":"TheBigDay",
			"data":{
				"text":{
					"paragraph":[
						{"content":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."},
						{"content":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."},
						{"content":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."},
						{"content":"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."}
					]
				},
				"img":[]
			},
		},
		{
			"view_id":"Proposal",
			"controller":"Proposal",
			"data":{
				"text":{},
				"img":[
					"http://localhost:8080/img-origin/rose-bottom.jpg",
					"http://localhost:8080/img-origin/rose-top.jpg"
				]
			}
		},
		{
			"view_id":"GoodNight",
			"controller":"GoodNight",
			"data":{
				"text":{},
				"img":[
					"http://localhost:8080/img-origin/nightsky-infinite.jpg"
				]
			}
		},
		{
			"view_id":"GoodMorning",
			"controller":"GoodMorning",
			"data":{
				"text":{
					"title":"GoodMorning"
				},
				"img":[]
			}
		},
		{
			"view_id":"LaVie",
			"controller":"LaVie",
			"data":{
				"text":{"title":"Meet our life"},
				"img":[
					"http://localhost:8080/img-origin/bouquet.png",
					"http://localhost:8080/img-origin/lavie1.jpg"
				]
			}
		},
		{
			"view_id":"Honeymoon",
			"controller":"Honeymoon",
			"data":{
				"text":{},
				"img":[
					"http://localhost:8080/img-origin/sunset.jpg"
				]
			}
		},
		{
			"view_id":"Contact",
			"controller":"Contact",
			"data":{
				"text":{},
				"img":[]
			}
		}
	]
};